<?php
/**
 * @file
 * Module file for views_cache_bully.
 */

/**
 * Implements hook_form_form_id_alter().
 */
function views_cache_bully_form_views_ui_admin_settings_advanced_alter(&$form, &$form_state, $form_id) {
  unset($form['cache']['clear_cache']);
  unset($form['cache']['views_skip_cache']);
  $form['cache']['views_cache_bully'] = array(
    '#markup' => t('Views Cache Bully has disabled these settings.'),
  );
}

/**
 * Implements hook_views_post_render().
 */
function views_cache_bully_views_post_render(&$view, &$output, &$cache) {
  // Unnecessary? since views_plugin_cache_none = views_plugin_cache_time.
  if ($cache['options']['results_lifespan'] == 0 || $cache['options']['output_lifespan'] == 0) {
    $cache['options']['results_lifespan'] = variable_get('views_cache_bully_results_lifespan', 3600);
    $cache['options']['output_lifespan']  = variable_get('views_cache_bully_output_lifespan', 3600);
  }
}

/**
 * Implements hook_views_api().
 */
function views_cache_bully_views_api() {
  return array('api' => 3);
}
